# part 1
# using score info from UWvMSU_1-22-13.txt generate a graph
# hint : generate a dataframe with a cumulative score for each team whenever either team scores
library(ggplot2)
setwd('/Users/laurenlatimer/Biocomputing/Biocomputing-Ex-10')
bball.data <- read.table("UWvMSU_1-22-13.txt", header=TRUE)
cumulative.scores <- data.frame(bball.data)

uw.score <- 0
msu.score <- 0 

for (i in 1:nrow(cumulative.scores)){
  if (cumulative.scores[i,2]=="UW"){
    uw.score <- uw.score + cumulative.scores[i, 3]
    cumulative.scores[i, 3] <- uw.score
  }
  else{
    msu.score <- msu.score + cumulative.scores[i, 3]
    cumulative.scores[i, 3] <- msu.score
  }
}

ggplot(cumulative.scores, aes(x = time, y = score, color = team)) +
  geom_step() +
  scale_color_manual(values = c("UW" = "red", "MSU" = "darkgreen")) +
  labs(title = "Michigan State vs. Wisconsin Score over Time",
       x = "Time",
       y = "Cumulative Score",
       color = "Team")

# part 2
# write a game for the user to guess a number between 1-100 randomly generated by the computer
# returns 'lower', 'higher', or 'correct!' based on the guess
# player can guess up to 10 times

print("I'm thinking of a number 1-100... You get 10 guesses!")
random.number <- sample(1:100, size=1)
for (i in 1:10){
  guess <- as.integer(readline(prompt = "Guess a number between 1-100: "))
  if (random.number<guess){
    print("lower")
    print(paste("Tries remaining:", 10 - i))
  } else if (random.number>guess){
    print("higher")
    print(paste("Tries remaining:", 10 - i))
  } else {
    print("correct!")
    break
  }
}
